import { Product } from '@/types';

export const PRODUCTS: Product[] = [
  // Joggers
  {
    id: 'joggers-1',
    name: 'Classic Black Joggers',
    description: 'Comfortable and stylish black joggers perfect for everyday wear. Made with premium cotton blend for maximum comfort.',
    price: 45.99,
    originalPrice: 59.99,
    category: 'joggers',
    image: '/products/joggers-black.jpg',
    images: ['/products/joggers-black.jpg', '/products/joggers-black-2.jpg'],
    variants: [
      { size: 'XS', color: 'Black', stock: 15 },
      { size: 'S', color: 'Black', stock: 20 },
      { size: 'M', color: 'Black', stock: 25 },
      { size: 'L', color: 'Black', stock: 18 },
      { size: 'XL', color: 'Black', stock: 12 },
      { size: 'XXL', color: 'Black', stock: 8 },
    ],
    rating: 4.8,
    reviews: 142,
    featured: true,
  },
  {
    id: 'joggers-2',
    name: 'Navy Blue Joggers',
    description: 'Sleek navy joggers with modern design. Perfect for athletic and casual occasions.',
    price: 48.99,
    category: 'joggers',
    image: '/products/joggers-navy.jpg',
    images: ['/products/joggers-navy.jpg'],
    variants: [
      { size: 'XS', color: 'Navy', stock: 12 },
      { size: 'S', color: 'Navy', stock: 18 },
      { size: 'M', color: 'Navy', stock: 22 },
      { size: 'L', color: 'Navy', stock: 16 },
      { size: 'XL', color: 'Navy', stock: 10 },
    ],
    rating: 4.7,
    reviews: 98,
    featured: true,
  },
  {
    id: 'joggers-3',
    name: 'Grey Melange Joggers',
    description: 'Elegant grey melange joggers with a contemporary fit. Versatile for all seasons.',
    price: 49.99,
    category: 'joggers',
    image: '/products/joggers-grey.jpg',
    images: ['/products/joggers-grey.jpg'],
    variants: [
      { size: 'S', color: 'Grey', stock: 14 },
      { size: 'M', color: 'Grey', stock: 20 },
      { size: 'L', color: 'Grey', stock: 17 },
      { size: 'XL', color: 'Grey', stock: 11 },
    ],
    rating: 4.9,
    reviews: 167,
    featured: true,
  },

  // Sweatshirts
  {
    id: 'sweatshirt-1',
    name: 'Premium Black Sweatshirt',
    description: 'Cozy and warm sweatshirt made from premium cotton. Perfect for layering or standalone wear.',
    price: 54.99,
    originalPrice: 69.99,
    category: 'sweatshirts',
    image: '/products/sweatshirt-black.jpg',
    images: ['/products/sweatshirt-black.jpg'],
    variants: [
      { size: 'XS', color: 'Black', stock: 16 },
      { size: 'S', color: 'Black', stock: 22 },
      { size: 'M', color: 'Black', stock: 28 },
      { size: 'L', color: 'Black', stock: 19 },
      { size: 'XL', color: 'Black', stock: 13 },
      { size: 'XXL', color: 'Black', stock: 9 },
    ],
    rating: 4.9,
    reviews: 256,
    featured: true,
  },
  {
    id: 'sweatshirt-2',
    name: 'Charcoal Sweatshirt',
    description: 'Sophisticated charcoal sweatshirt with a relaxed fit. Great for casual or smart-casual looks.',
    price: 56.99,
    category: 'sweatshirts',
    image: '/products/sweatshirt-charcoal.jpg',
    images: ['/products/sweatshirt-charcoal.jpg'],
    variants: [
      { size: 'S', color: 'Charcoal', stock: 11 },
      { size: 'M', color: 'Charcoal', stock: 19 },
      { size: 'L', color: 'Charcoal', stock: 15 },
      { size: 'XL', color: 'Charcoal', stock: 8 },
    ],
    rating: 4.8,
    reviews: 134,
    featured: true,
  },
  {
    id: 'sweatshirt-3',
    name: 'Burgundy Sweatshirt',
    description: 'Rich burgundy sweatshirt for a bold statement. Premium quality and perfect fit.',
    price: 57.99,
    category: 'sweatshirts',
    image: '/products/sweatshirt-burgundy.jpg',
    images: ['/products/sweatshirt-burgundy.jpg'],
    variants: [
      { size: 'XS', color: 'Burgundy', stock: 10 },
      { size: 'S', color: 'Burgundy', stock: 16 },
      { size: 'M', color: 'Burgundy', stock: 21 },
      { size: 'L', color: 'Burgundy', stock: 14 },
      { size: 'XL', color: 'Burgundy', stock: 9 },
    ],
    rating: 4.7,
    reviews: 89,
    featured: false,
  },

  // Kids Dresses
  {
    id: 'kids-dress-1',
    name: 'Floral Kids Dress',
    description: 'Adorable floral print dress for girls. Comfortable and perfect for special occasions.',
    price: 35.99,
    originalPrice: 45.99,
    category: 'kids-dresses',
    image: '/products/kids-dress-floral.jpg',
    images: ['/products/kids-dress-floral.jpg'],
    variants: [
      { size: '2Y', color: 'Floral', stock: 12 },
      { size: '3Y', color: 'Floral', stock: 18 },
      { size: '4Y', color: 'Floral', stock: 20 },
      { size: '5Y', color: 'Floral', stock: 15 },
      { size: '6Y', color: 'Floral', stock: 11 },
    ],
    rating: 4.9,
    reviews: 178,
    featured: true,
  },
  {
    id: 'kids-dress-2',
    name: 'Classic Navy Kids Dress',
    description: 'Timeless navy dress for boys and girls. Versatile for school and formal events.',
    price: 38.99,
    category: 'kids-dresses',
    image: '/products/kids-dress-navy.jpg',
    images: ['/products/kids-dress-navy.jpg'],
    variants: [
      { size: '3Y', color: 'Navy', stock: 14 },
      { size: '4Y', color: 'Navy', stock: 22 },
      { size: '5Y', color: 'Navy', stock: 18 },
      { size: '6Y', color: 'Navy', stock: 13 },
      { size: '7Y', color: 'Navy', stock: 10 },
    ],
    rating: 4.8,
    reviews: 145,
    featured: true,
  },
  {
    id: 'kids-dress-3',
    name: 'Elegant Pink Party Dress',
    description: 'Perfect for parties and celebrations. Elegant pink dress with comfortable fit.',
    price: 42.99,
    category: 'kids-dresses',
    image: '/products/kids-dress-pink.jpg',
    images: ['/products/kids-dress-pink.jpg'],
    variants: [
      { size: '2Y', color: 'Pink', stock: 10 },
      { size: '3Y', color: 'Pink', stock: 15 },
      { size: '4Y', color: 'Pink', stock: 19 },
      { size: '5Y', color: 'Pink', stock: 12 },
      { size: '6Y', color: 'Pink', stock: 8 },
    ],
    rating: 5.0,
    reviews: 203,
    featured: true,
  },

  // Adult Dresses
  {
    id: 'adult-dress-1',
    name: 'Elegant Black Evening Dress',
    description: 'Sophisticated black evening dress perfect for formal occasions. Premium fabric with perfect drape.',
    price: 89.99,
    originalPrice: 119.99,
    category: 'adult-dresses',
    image: '/products/adult-dress-black-evening.jpg',
    images: ['/products/adult-dress-black-evening.jpg'],
    variants: [
      { size: 'XS', color: 'Black', stock: 7 },
      { size: 'S', color: 'Black', stock: 12 },
      { size: 'M', color: 'Black', stock: 15 },
      { size: 'L', color: 'Black', stock: 10 },
      { size: 'XL', color: 'Black', stock: 6 },
    ],
    rating: 4.9,
    reviews: 234,
    featured: true,
  },
  {
    id: 'adult-dress-2',
    name: 'Casual Midi Dress',
    description: 'Comfortable and stylish midi dress for everyday wear. Perfect for any season.',
    price: 64.99,
    category: 'adult-dresses',
    image: '/products/adult-dress-midi.jpg',
    images: ['/products/adult-dress-midi.jpg'],
    variants: [
      { size: 'XS', color: 'Beige', stock: 11 },
      { size: 'S', color: 'Beige', stock: 17 },
      { size: 'M', color: 'Beige', stock: 21 },
      { size: 'L', color: 'Beige', stock: 14 },
      { size: 'XL', color: 'Beige', stock: 9 },
      { size: 'XXL', color: 'Beige', stock: 5 },
    ],
    rating: 4.7,
    reviews: 167,
    featured: true,
  },
  {
    id: 'adult-dress-3',
    name: 'Burgundy Cocktail Dress',
    description: 'Chic burgundy cocktail dress for special events. Modern design with classic elegance.',
    price: 79.99,
    category: 'adult-dresses',
    image: '/products/adult-dress-burgundy.jpg',
    images: ['/products/adult-dress-burgundy.jpg'],
    variants: [
      { size: 'S', color: 'Burgundy', stock: 8 },
      { size: 'M', color: 'Burgundy', stock: 13 },
      { size: 'L', color: 'Burgundy', stock: 11 },
      { size: 'XL', color: 'Burgundy', stock: 7 },
    ],
    rating: 4.8,
    reviews: 112,
    featured: true,
  },
];

export const CATEGORIES = [
  { id: 'joggers', name: 'Joggers', count: 3 },
  { id: 'sweatshirts', name: 'Sweatshirts', count: 3 },
  { id: 'kids-dresses', name: "Kids' Dresses", count: 3 },
  { id: 'adult-dresses', name: "Adult Dresses", count: 3 },
];
